# X settings
xset -dpms
xset s 300 10
xset r rate 300 50
xrdb -merge $XDG_CONFIG_HOME/x11/Xresources
setxkbmap -option caps:escape
setxkbmap -layout us,ir -option grp:alt_shift_toggle
xinput set-prop "ELAN0501:00 04F3:3019 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0501:00 04F3:3019 Touchpad" "libinput Natural Scrolling Enabled" 1
xwallpaper --stretch $XDG_DATA_HOME/bg.jpg

# Autostart
redshift -O 5500 &
xss-lock -n dim-screen -l -- slock &
batterynotif &
dunst &
mpd &
picom &
dwmbar &
syncthing --no-browser >/dev/null 2>&1 &

# WM
exec dwm
