# X settings
xset -dpms
xset s 900 10
xset r rate 300 50
xrdb -merge $XDG_CONFIG_HOME/x11/Xresources
setxkbmap -option caps:none
setxkbmap -layout us,ir -option grp:alt_shift_toggle
xinput set-prop "ELAN0501:00 04F3:3019 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0501:00 04F3:3019 Touchpad" "libinput Natural Scrolling Enabled" 1

# Autostart
gensec &
xbanish -i all -t 15 &
redshift -O 5500 &
xwallpaper --stretch $XDG_DATA_HOME/bg.jpg &
xss-lock -n dim-screen -l -- slock loginctl suspend -i &
batterynotif &
mpd
pgrep mpd-notify || mpd-notify &
pgrep dwmbar || dwmbar &
dunst &
syncthing --no-browser &
gentoo-pipewire-launcher &

# WM
dwm 2>$XDG_DATA_HOME/dwm.log
