#!/bin/sh
# Description: A simple powermenu with dmenu
# Dependencies: dmenu
# Shell: POSIX compliant

SELECT=$(printf "Poweroff\nRestart\nLogoff\nLockscreen" |
	dmenu -h 29 -sb '#FABD2F' -nf '#fff' -sf '#000')

LOGOFF_CMD="bspc quit"

case $SELECT in
	Poweroff)
		notify-send -i system-shutdown "Shutting down..."
		sleep 0.75
		poweroff
		;;
	Restart)
		notify-send -i system-reboot "Restarting..."
		sleep 0.75
		reboot
		;;
	Logoff)
		notify-send -i cs-user "Logging off..." -u low
		sleep 0.75
		$LOGOFF_CMD
		;;
	Lockscreen)
		notify-send -i gnome-lockscreen "Lockscreen..." -u low
		sleep 0.75
		xset s activate
		xset dpms force off
		;;
esac
