#!/bin/sh
# Description: Calculate and show the result
# Dependencies: dmenu, bc
# Shell: POSIX compliant

while true; do
	calc=$(printf "" | dmenu -p "Calc:" -h 29)

	[ -z "$calc" ] && exit 1

	echo "scale=3; $calc" | bc | sed '/\./ s/\.*0*$//g' | dmenu -r -p "Result" -sb "#504945" -h 29
done
