#!/bin/sh
# Description: dmenu "pass" manager
# Dependencies: pass
# Shell: POSIX compliant

select=$(printf "generate a password\nshow password list" | dmenu -h 29)

case $select in
	"generate a password")
		pass_name=$(printf "" | dmenu -p "Name:")
		[ -z "$pass_name" ] && exit 1
		pass generate -c "$pass_name" 2>/dev/null &&
		notify-send "PASS" \
			"password ""$pass_name"" has been copied to clipboard" -i password
		;;
	"show password list")
		passmenu 2>/dev/null
		;;
esac
