#!/bin/sh
# Description: manage network with iwctl
# Dependencies: dmenu, iwd
# Shell: POSIX compliant

INTERFACE="wlan0"
connected=$(iwctl station "$INTERFACE" show |
	sed 's/\x1b\[[0-9;]*m//g' |
	grep 'Connected' |
	sed 's/^\s*//g;s/\s*$//g')

SELECT=$(printf "Connect to a network\nDisconnect current network\nForget a network\n %s" "$([ -n "$connected" ] && echo "::$connected::")" | dmenu -h 29)

case $SELECT in
	"Connect to a network")
		notify-send "IWCTL" "searching for networks" -i wifi-radar -u low
		iwctl station "$INTERFACE" scan

		# Give enough time to iwctl to find networks
		sleep 2

		networks=$(iwctl station "$INTERFACE" get-networks |
			sed 's/>//g' |
			sed 's/\x1b\[[0-9;]*m//g' |
			tail -n +5 | head -n -1 |
			sed 's/psk\s*\**//g' |
			sed 's/^\s*//g;s/\s*$//g' |
			sort)

		network=$(echo "$networks" | dmenu -l 10)

		[ -z "$network" ] && exit 1

		password=$(printf 'No\nYes' | dmenu -h 29 -p "Password required?")

		[ -z "$password" ] && exit 1

		if [ "$password" = "No" ]; then
			iwctl station "$INTERFACE" connect "$network" &&
				notify-send "IWCTL" "Connected to $network" -i wifi-radar && exit 0

			# failure
			notify-send "IWCTL" "Failed connecting to $network" \
				-i notification-network-wireless-disconnected
		elif [ "$password" = "Yes" ]; then
			dmenu -h 29 -p "enter password" -P <&- |
				xargs -r -I{} iwctl station -P {} "$INTERFACE" connect "$network" &&
				notify-send "IWCTL" "Connected to $network" -i wifi-radar && exit 0

			# failure
			notify-send "IWCTL" "Failed connecting to $network" \
				-i notification-network-wireless-disconnected
		else
			notify-send "IWCTL" "Please select between two options" \
				-i system-error
		fi

		;;
	"Disconnect current network")
		iwctl station "$INTERFACE" disconnect
		;;
	"Forget a network")
		networks=$(iwctl known-networks list |
			sed 's/>//g' |
			sed 's/\x1b\[[0-9;]*m//g' |
			tail -n +5 | head -n -1 |
			sed 's/psk.*$//g' |
			sed 's/^\s*//g;s/\s*$//g' |
			sort)

		network=$(echo "$networks" | dmenu -l 10)

		echo "$network"

		[ -z "$network" ] && exit 1

		iwctl known-networks "$network" forget
		;;
esac
