#!/bin/sh
# Description: A simple powermenu with dmenu
# Dependencies: dmenu
# Shell: POSIX compliant

SELECT=$(printf "Poweroff\nRestart\nLogoff\nSuspend" |\
        dmenu -h 29 -sb '#FABD2F' -nf '#fff' -sf '#000')

LOGOFF_CMD="bspc quit"

case $SELECT in
        Power*)
                notify-send -i system-shutdown "Shutting down..."
                sleep 0.75
                poweroff
                ;;
        Rest*)
                notify-send -i system-reboot "Restarting..."
                sleep 0.75
                reboot
                ;;
        Log*)
                notify-send -i cs-user "Logging off..."
                sleep 0.75
                $LOGOFF_CMD
                ;;
        Sus*)
                notify-send -i gnome-lockscreen "Suspend..."
                sleep 0.75
                systemctl suspend
                ;;
esac
