#!/bin/sh
MOVIE_FOLDER="/run/media/sda3/Movie/ /home/morteza/Downloads"
EXCLUDE_MOVIE="**Telegram**" # based on pattern

du -a $MOVIE_FOLDER --exclude=$EXCLUDE_MOVIE | \
        cut -f2 |cut -c -90 | grep "mp4\|mkv" --color=never | \
        dmenu -l 10 -bw 2 -c |xargs -I{} mpv "{}"
