# Key Bindings

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=SUPER,d,spawn,fuzzel
bind=SUPER,Return,spawn,foot

# quit program
bind=SUPER+SHIFT,q,killclient,

# switch window focus
bind=SUPER,Tab,focuslast,dispatch
bind=SUPER,k,focusstack,prev
bind=SUPER,j,focusstack,next
bind=SUPER,SPACE,zoom

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal
bind=ALT,Tab,toggleoverview
bind=SUPER,s,togglefloating
bind=SUPER,t,setlayout,tile
bind=SUPER,m,setlayout,monocle
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,f,togglefakefullscreen
bind=SUPER,i,minimized
bind=SUPER+SHIFT,I,restore_minimized

# switch tag view
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# move client to the tag and focus it
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# resizewin like dmw
bind=SUPER,h,resizewin,-50,0
bind=SUPER,l,resizewin,+50,0

# mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

# scratchpad
bind=SUPER,u,toggle_named_scratchpad,scratchpad,none,foot --app-id scratchpad
windowrule=isnamedscratchpad:1,width:800,height:540,appid:scratchpad

# programs
bind=CTRL+SUPER,equal,spawn,dmenupass
bind=CTRL+SUPER,p,spawn,dmenupower
bind=CTRL+SUPER,m,spawn,open-ncmpcpp
bind=SUPER,Print,spawn,grimshot

# audio controls
bind=none,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bind=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=none,XF86AudioMicMute,spawn_shell,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && pkill -RTMIN+8 waybar

# brightness (laptop)
bind=none,XF86MonBrightnessUp,spawn,brightnessctl -e4 -n2 set 5%+
bind=none,XF86MonBrightnessDown,spawn,brightnessctl -e4 -n2 set 5%-

# media controls
bind=none,XF86AudioNext,spawn,playerctl next
bind=none,XF86AudioPrev,spawn,playerctl previous
bind=none,XF86AudioPause,spawn,playerctl play-pause
bind=none,XF86AudioPlay,spawn,playerctl play-pause

# media controls (non-multimedia keyboard)
bind=none,End,spawn,playerctl next
bind=none,Home,spawn,playerctl previous
bind=SUPER,End,spawn,playerctl position 10+
bind=SUPER,Home,spawn,playerctl position 10-
bind=none,Insert,spawn,playerctl play-pause
bind=SUPER,Insert,spawn,playerctl stop

# volume controls (non-multimedia keyboard)
bind=none,Page_Up,spawn,wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bind=none,Page_Down,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=none,Pause,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=none,Scroll_Lock,spawn_shell,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && pkill -RTMIN+8 waybar

# external monitor brightness
bind=none,F11,spawn,ddcutil setvcp 10 - 10 --skip-ddc-checks --bus 3
bind=none,F12,spawn,ddcutil setvcp 10 + 10 --skip-ddc-checks --bus 3

# notifications
bind=CTRL+SHIFT,space,spawn,makoctl restore
bind=CTRL,space,spawn,makoctl dismiss

# screenshot
bind=ALT,F9,spawn,scrcap
