# browsers -> tag 2
windowrule=tags:2,appid:^firefox$
windowrule=tags:2,appid:^brave-browser$
windowrule=tags:2,appid:^chromium$

# telegram -> tag 3
windowrule=tags:3,appid:^org.telegram.desktop$

# mpv -> tag 4
windowrule=tags:4,appid:^mpv$

# steam -> tag 4 + tagsilent
windowrule=tags:4,istagsilent:1,appid:^steam$

# zathura -> tag 5
windowrule=tags:5,appid:^org.pwmt.zathura$

# ncmpcpp -> tag 6 + floating
windowrule=isfloating:1,tags:6,title:^ncmpcpp$
windowrule=width:768,height:432,title:^ncmpcpp$

# Thunderbird -> tag 7
windowrule=tags:7,appid:^org.mozilla.Thunderbird$

# qBittorrent -> tag 8 + floating
windowrule=isfloating:1,tags:8,appid:^org.qbittorrent.qBittorrent$
windowrule=width:1056,appid:^org.qbittorrent.qBittorrent$

# sharing screen popup -> tag 9
windowrule=tags:9,istagsilent:1,title:.* is sharing your screen\.$

# floating apps
windowrule=isfloating:1,appid:^Clockify$
windowrule=isfloating:1,appid:^oblivion-desktop$
windowrule=isfloating:1,appid:^Windscribe$
windowrule=isfloating:1,appid:^hiddify$
windowrule=isfloating:1,appid:^localsend$
windowrule=isfloating:1,appid:^com.obsproject.Studio$
windowrule=isfloating:1,appid:^com.github.persepolisdm.persepolis$
windowrule=isfloating:1,title:^Write:.*
windowrule=isfloating:1,title:^floating$
windowrule=width:800,height:540,title:^floating$
