#!/bin/bash

# File info and other variables
  s=" | "
  filename=$(basename "$1")
  filesize=$(du -Hh "$1" | cut -f 1)
  geometry=$(identify -format '%wx%h' "$1[0]")

# Bar Line Content
  echo "ctrl+x to execute commands${s}${filesize}${s}${geometry}${s}${filename}"
