#!/bin/sh

while read file; do
  case "$1" in

# Set Wallpaper
    "b")
    xwallpaper --stretch "$file" &&
      cp "$file" "$HOME/.config/wallp.jpg" &
    ;;

# Rotate +90
    "r")
    convert -rotate 90 "$file" "$file"
    ;;

# Rotate -90
    "R")
    convert -rotate -90 "$file" "$file"
    ;;

# Flip Image
    "f")
    convert -flop "$file" "$file"
    ;;

# Yank
    "y")
    xclip -selection clipboard -t image/png -i "$file" && \
      notify-send "$file copied to clipboard" &
    ;;

# Delete
    "d")
    [ "$(printf "No\\nYes" | dmenu -h 29 -sb "#61AFEF" -sf "#000" \
      -p "Really delete $file?")" = "Yes" ] && rm "$file" \
      && notify-send -i trashindicator "$file deleted."
    ;;

  esac
done
