general {
    lock_cmd = pidof waylock || waylock
    before_sleep_cmd = waylock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 290
    on-timeout = dim
}

listener {
    timeout = 300
    on-timeout = waylock
}

listener {
    timeout = 310
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
