#!/bin/sh

# bspc monitor
bspc monitor -d 1 2 3 4 5 6

# border & gaps
bspc config border_width         1
bspc config window_gap          10

# general
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config directional_focus_tightness low # Allow focusing to floating windows with keyboard
bspc config removal_adjustment false # Avoid screwing windows up after closing the biggest forth window

# colors
bspc config focused_border_color '#64656A'
bspc config normal_border_color '#0f0f0f'

# rules
bspc rule -a firefox:Navigator desktop='^2' follow=on #Main window
bspc rule -a firefox:Toolkit state=floating rectangle=900x500+0+0 sticky=on #Picture-in-Picture window
bspc rule -a firefox:Browser state=floating #About window
bspc rule -a firefox:Places state=floating #Bookmark window
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Zathura desktop='^4' state=tiled follow=on
bspc rule -a ncmpcpp state=floating desktop=^5 follow=on
bspc rule -a Joplin desktop='^6' follow=on
bspc rule -a qBittorrent state=floating
