#! /bin/sh

sxhkd &

# fix cursor displaying as X when not over windows
xsetroot -cursor_name left_ptr &

# bspc monitor -d term firefox telegram movie files
bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#1d2020'
bspc config normal_border_color '#282C34'

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Zathura desktop='^5' state=fullscreen follow=on
bspc rule -a persepolis state=floating desktop='^5' follow=on
bspc rule -a Alacritty:ncmpcpp -o desktop=^4 state=floating follow=on
bspc rule -a libreoffice desktop='^5' follow=on
bspc rule -a Alacritty:bc state=floating
bspc rule -a Pulseaudio-equalizer-gtk state=floating
bspc desktop 3 -l monocle

# picom
picom --experimental-backends &

# xfce power manager
xfce4-power-manager &

# set wallpaper
xwallpaper --stretch .config/wallp.jpg &

# polybar
$HOME/.config/polybar/launch.sh

# nm-applet
nm-applet &

# redshift
redshift &

# repeat rate/delay
xset r rate 300 30

# add persian layout with windows variant keyboard
setxkbmap -layout us,ir -variant ,pes_win -option grp:alt_shift_toggle

# touchpad
# enable tapping, natural scrolling
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
