#!/bin/sh

# helper to execute commands
exec_cmd() {
		which $1 && (pidof $1 || $@&)
}

# fix cursor displaying X when not over windows
xsetroot -cursor_name left_ptr

# bspc monitor
bspc monitor -d 1 2 3 4 5

# border & gaps
bspc config border_width         1
bspc config window_gap          10

# general
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config directional_focus_tightness low

# colors
bspc config focused_border_color '#a06f97'
bspc config normal_border_color '#0f0f0f'

# rules
bspc rule -r "*"
bspc rule -a firefox:Navigator desktop='^2' follow=on #Main window
bspc rule -a firefox:Toolkit state=floating rectangle=900x500+0+0 sticky=on #Picture-in-Picture window
bspc rule -a firefox:Browser state=floating #About window
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Alacritty:ncmpcpp desktop=^5 state=floating follow=on
bspc rule -a Zathura desktop='^4' state=tiled follow=on
bspc rule -a persepolis desktop='^5' state=floating follow=on
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a Lxappearance:lxappearance state=floating

# screen lock
xset s 420 10
exec_cmd xss-lock -n $HOME/.config/scripts/dim-screen -l -- slock

# sxhkd
export SXHKD_SHELL='/bin/sh'
exec_cmd sxhkd

# picom
exec_cmd picom --experimental-backends

# xfce power manager
exec_cmd xfce4-power-manager

# polybar
pkill polybar
exec_cmd polybar top -r

# nm-applet
exec_cmd nm-applet

# redshift
exec_cmd redshift -t 5000:4000 -l 35:51

# dunst
exec_cmd dunst

# batterynotif
pkill batterynotif
setsid -f $HOME/.config/scripts/batterynotif

# set wallpaper
xwallpaper --stretch $HOME/.config/wallp.jpg

# repeat rate/delay
xset r rate 300 30

# add persian layout with windows variant keyboard
setxkbmap -layout us,ir -variant ,pes_win -option grp:alt_shift_toggle

# touchpad
# enable tapping, natural scrolling
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Natural Scrolling Enabled" 1
