#!/bin/sh

while read -r file
do
case "$1" in
	"w")
		setbg "$file" &
		;;
	"r")
		convert -rotate 90 "$file" "$file"
		;;
	"d")
		dragon-drop "$file" &
		;;
	"x")
		prompt "Remove this image?" && rm "$file" && notify-send "$file deleted"
		;;
	"X")
		rm "$file" && notify-send "Marked files deleted!"
		;;
esac
done
