vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("x", "<", "<gv")
vim.keymap.set("x", ">", ">gv")
vim.keymap.set("x", "J", ":m '>+1<CR>gv=gv", { silent = true })
vim.keymap.set("x", "K", ":m '<-2<CR>gv=gv", { silent = true })
vim.keymap.set("n", "<leader>o", "<cmd>setlocal spell!<cr>", { desc = "Toggle spell checking" })
vim.keymap.set("ca", "W", "w")
vim.keymap.set("n", "<space><space>", "<cmd>FzfLua files<cr>", { desc = "FZF: Find Files" })
vim.keymap.set("n", "<space>g", "<cmd>FzfLua live_grep<cr>", { desc = "FZF: Live grep" })
vim.keymap.set("x", "<space>g", "<cmd>FzfLua grep_visual<cr>", { desc = "FZF: Live grep visually selected string" })
vim.keymap.set("n", "<space>o", "<cmd>FzfLua oldfiles<cr>", { desc = "FZF: Oldfiles" })
vim.keymap.set("n", "<space>b", "<cmd>FzfLua buffers<cr>", { desc = "FZF: Buffers" })
vim.keymap.set("n", "<leader><leader>", "<cmd>FzfLua resume<cr>", { desc = "FZF: Resume" })
vim.keymap.set("n", "z=", "<cmd>FzfLua spell_suggest<cr>", { desc = "FZF: Spell Suggest" })
vim.keymap.set("n", "-", "<cmd>=MiniFiles.open(vim.api.nvim_buf_get_name(0), false)<cr>", { desc = "File explorer" })
vim.keymap.set("n", "<space>u", "<cmd>Undotree<cr>", { desc = "Undotree" })
vim.keymap.set("n", "gS", "<cmd>TSJToggle<cr>", { desc = "TreeSJ" })
