local set = vim.o
local g = vim.g

set.number = true
set.relativenumber = true
set.hlsearch = false
set.clipboard = "unnamedplus"
set.splitbelow = true
set.showmode = false
set.splitright = true
set.tabstop = 4
set.shiftwidth = 4
set.shiftwidth = 4
set.backup = false
set.swapfile = false
set.smartindent = true
set.signcolumn = "number"
set.termguicolors = true
set.cursorline = true
set.lazyredraw = true
set.scrolloff = 8
set.updatetime = 300
set.pumheight = 10
set.breakindent = true
set.laststatus = 3
set.title = true
set.ignorecase = true
set.smartcase = true
set.mouse = ""
set.path = "**"
set.spelllang = "en_us"
g.mapleader = " "
