##################################
#         Global settings        #
##################################
server_names = ['adguard-dns-family']
listen_addresses = ['127.0.0.1:53']
require_dnssec = true
require_nofilter = false
block_ipv6 = true

########################################
#            Static entries            #
########################################
[static]
  [static.'adguard-dns-family']
  	stamp = 'sdns://AQIAAAAAAAAAFDE3Ni4xMDMuMTMwLjEzMjo1NDQzILgxXdexS27jIKRw3C7Wsao5jMnlhvhdRUXWuMm1AFq6ITIuZG5zY3J5cHQuZmFtaWx5Lm5zMS5hZGd1YXJkLmNvbQ'
